name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/rokgroup/therokgroup
          
          # Pull latest code
          git pull origin main
          
          # Activate virtual environment and update packages
          source env/bin/activate
          pip install -r requirements.txt
          
          # Restart the service to apply changes
          sudo systemctl restart flaskapp